name: 'airline_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'airline_dbt'

# Optionally specify a custom list of directories for objects in DBT projects
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Specify a custom list of directories to be removed by the dbt clean command
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  airline_dbt:
    staging:
      +materialized: view
    int:
      +materialized: ephemeral      
    marts:
      +materialized: table


