name: pr_to_main_dbt
on:
  pull_request:

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  pr_to_main_dbt:
    name: pr_to_main_dbt
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.11.x"

      ## Cache Pip wheel files
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      ## Install Python dependencies & Dbt packages
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          dbt deps

      - name: Install extension for Postgres schema
        run: |
          dbt run-operation create_extensions

      - name: Run Seed
        run: |
          dbt seed --target dev -f

      # run and tested.
      - name: Run all models
        id: run_all_models
        if: always() && steps.download_dbt_manifest.outcome != 'success'
        run: |
          dbt run --target dev

      - name: Test all models
        id: test_all_models
        if: always() && steps.download_dbt_manifest.outcome != 'success'
        run: |
          dbt test --target dev
